version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: findash_postgres
    environment:
      POSTGRES_DB: findash
      POSTGRES_USER: findash
      POSTGRES_PASSWORD: findash
    ports:
      - "1901:5432"
    volumes:
      - postgres_dados:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U findash -d findash"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_dados:
