import type { LancamentoRecorrenteDadosSimulados } from "../../tipos/recorrencias/lancamento-recorrente.tipos";
import {
  PeriodicidadeRecorrenciaSistema,
} from "../../tipos/recorrencias/lancamento-recorrente.tipos";
import {
  ModoMovimentacaoSistema,
  TipoMovimentacaoSistema,
} from "../../tipos/sistema/financeiro.tipos";

const usuarioUmId = "usuario_001";
const usuarioDoisId = "usuario_002";

const carteiraUsuarioUmId = "carteira_usuario_001_principal";

const recorrenciaDespesaId = "recorrencia_001";
const recorrenciaReceitaId = "recorrencia_002";
const recorrenciaOutroUsuarioId = "recorrencia_777";

const usuariosCarga = Array.from({ length: 160 }, (_, indice) => {
  const sufixo = String(indice + 1).padStart(3, "0");
  return `usuario_recorrencia_${sufixo}`;
});

export const lancamentoRecorrenteDadosSimulados: LancamentoRecorrenteDadosSimulados = {
  entradas: {
    criacaoDespesaMensalUsuarioUm: {
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmId,
      descricao: "Assinatura de streaming",
      modo: ModoMovimentacaoSistema.CARTAO_CREDITO,
      tipo: TipoMovimentacaoSistema.SAIDA,
      valor: -120,
      periodicidade: PeriodicidadeRecorrenciaSistema.MENSAL,
      dia_execucao: 31,
      data_inicio: "2026-01-01",
    },
    criacaoReceitaMensalUsuarioUm: {
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmId,
      descricao: "Salario",
      modo: ModoMovimentacaoSistema.TRANSFERENCIA,
      tipo: TipoMovimentacaoSistema.ENTRADA,
      valor: 3500,
      periodicidade: PeriodicidadeRecorrenciaSistema.MENSAL,
      dia_execucao: 5,
      data_inicio: "2026-01-01",
    },
    criacaoComValorInvalido: {
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmId,
      descricao: "Recorrencia invalida",
      modo: ModoMovimentacaoSistema.PIX,
      tipo: TipoMovimentacaoSistema.SAIDA,
      valor: 0,
      periodicidade: PeriodicidadeRecorrenciaSistema.MENSAL,
      dia_execucao: 10,
      data_inicio: "2026-01-01",
    },
    pausaRecorrenciaUsuarioUm: {
      usuario_id: usuarioUmId,
      recorrencia_id: recorrenciaDespesaId,
    },
    reativacaoRecorrenciaUsuarioUm: {
      usuario_id: usuarioUmId,
      recorrencia_id: recorrenciaDespesaId,
    },
    encerramentoRecorrenciaUsuarioUm: {
      usuario_id: usuarioUmId,
      recorrencia_id: recorrenciaDespesaId,
      data_fim: "2026-06-30",
    },
    geracaoOcorrenciasPrimeiroTrimestre: {
      usuario_id: usuarioUmId,
      data_inicial: "2026-01-01",
      data_final: "2026-03-31",
    },
    geracaoOcorrenciasRecorrenciaPausada: {
      usuario_id: usuarioUmId,
      data_inicial: "2026-04-01",
      data_final: "2026-04-30",
    },
    edicaoProximasOcorrenciasUsuarioUm: {
      usuario_id: usuarioUmId,
      recorrencia_id: recorrenciaDespesaId,
      data_corte: "2026-04-01",
      novo_valor: -150,
      novo_dia_execucao: 10,
    },
    pausaRecorrenciaOutroUsuario: {
      usuario_id: usuarioUmId,
      recorrencia_id: recorrenciaOutroUsuarioId,
    },
    listagemRecorrenciasUsuarioUm: {
      usuario_id: usuarioUmId,
      incluir_pausados: true,
      incluir_encerrados: true,
    },
    cargaMultiusuario: {
      usuario_ids: usuariosCarga,
      total_usuarios_esperado: 160,
      tempo_maximo_ms: 1400,
    },
  },
  resultados: {
    recorrenciaDespesaMensalCriada: {
      id: recorrenciaDespesaId,
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmId,
      descricao: "Assinatura de streaming",
      modo: ModoMovimentacaoSistema.CARTAO_CREDITO,
      tipo: TipoMovimentacaoSistema.SAIDA,
      valor: -120,
      periodicidade: PeriodicidadeRecorrenciaSistema.MENSAL,
      dia_execucao: 31,
      data_inicio: "2026-01-01",
      ativo: true,
      pausado: false,
      criado_em: "2026-03-03T13:10:00.000Z",
    },
    recorrenciaReceitaMensalCriada: {
      id: recorrenciaReceitaId,
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmId,
      descricao: "Salario",
      modo: ModoMovimentacaoSistema.TRANSFERENCIA,
      tipo: TipoMovimentacaoSistema.ENTRADA,
      valor: 3500,
      periodicidade: PeriodicidadeRecorrenciaSistema.MENSAL,
      dia_execucao: 5,
      data_inicio: "2026-01-01",
      ativo: true,
      pausado: false,
      criado_em: "2026-03-03T13:11:00.000Z",
    },
    recorrenciaPausada: {
      id: recorrenciaDespesaId,
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmId,
      descricao: "Assinatura de streaming",
      modo: ModoMovimentacaoSistema.CARTAO_CREDITO,
      tipo: TipoMovimentacaoSistema.SAIDA,
      valor: -120,
      periodicidade: PeriodicidadeRecorrenciaSistema.MENSAL,
      dia_execucao: 31,
      data_inicio: "2026-01-01",
      ativo: true,
      pausado: true,
      criado_em: "2026-03-03T13:10:00.000Z",
    },
    recorrenciaReativada: {
      id: recorrenciaDespesaId,
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmId,
      descricao: "Assinatura de streaming",
      modo: ModoMovimentacaoSistema.CARTAO_CREDITO,
      tipo: TipoMovimentacaoSistema.SAIDA,
      valor: -120,
      periodicidade: PeriodicidadeRecorrenciaSistema.MENSAL,
      dia_execucao: 31,
      data_inicio: "2026-01-01",
      ativo: true,
      pausado: false,
      criado_em: "2026-03-03T13:10:00.000Z",
    },
    recorrenciaEncerrada: {
      id: recorrenciaDespesaId,
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmId,
      descricao: "Assinatura de streaming",
      modo: ModoMovimentacaoSistema.CARTAO_CREDITO,
      tipo: TipoMovimentacaoSistema.SAIDA,
      valor: -120,
      periodicidade: PeriodicidadeRecorrenciaSistema.MENSAL,
      dia_execucao: 31,
      data_inicio: "2026-01-01",
      data_fim: "2026-06-30",
      ativo: false,
      pausado: false,
      criado_em: "2026-03-03T13:10:00.000Z",
    },
    recorrenciaEditadaProximasOcorrencias: {
      id: recorrenciaDespesaId,
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmId,
      descricao: "Assinatura de streaming",
      modo: ModoMovimentacaoSistema.CARTAO_CREDITO,
      tipo: TipoMovimentacaoSistema.SAIDA,
      valor: -150,
      periodicidade: PeriodicidadeRecorrenciaSistema.MENSAL,
      dia_execucao: 10,
      data_inicio: "2026-01-01",
      ativo: true,
      pausado: false,
      criado_em: "2026-03-03T13:10:00.000Z",
    },
    ocorrenciasPrimeiroTrimestre: [
      {
        id_ocorrencia: "ocorrencia_001",
        recorrencia_id: recorrenciaDespesaId,
        usuario_id: usuarioUmId,
        competencia: "2026-01",
        data_prevista: "2026-01-31",
        valor: -120,
        status: "lancada",
      },
      {
        id_ocorrencia: "ocorrencia_002",
        recorrencia_id: recorrenciaDespesaId,
        usuario_id: usuarioUmId,
        competencia: "2026-02",
        data_prevista: "2026-02-28",
        valor: -120,
        status: "lancada",
      },
      {
        id_ocorrencia: "ocorrencia_003",
        recorrencia_id: recorrenciaDespesaId,
        usuario_id: usuarioUmId,
        competencia: "2026-03",
        data_prevista: "2026-03-31",
        valor: -120,
        status: "pendente",
      },
    ],
    ocorrenciasRecorrenciaPausada: [],
    listagemRecorrenciasUsuarioUm: [
      {
        id: recorrenciaDespesaId,
        usuario_id: usuarioUmId,
        carteira_id: carteiraUsuarioUmId,
        descricao: "Assinatura de streaming",
        modo: ModoMovimentacaoSistema.CARTAO_CREDITO,
        tipo: TipoMovimentacaoSistema.SAIDA,
        valor: -120,
        periodicidade: PeriodicidadeRecorrenciaSistema.MENSAL,
        dia_execucao: 31,
        data_inicio: "2026-01-01",
        ativo: true,
        pausado: false,
        criado_em: "2026-03-03T13:10:00.000Z",
      },
      {
        id: recorrenciaReceitaId,
        usuario_id: usuarioUmId,
        carteira_id: carteiraUsuarioUmId,
        descricao: "Salario",
        modo: ModoMovimentacaoSistema.TRANSFERENCIA,
        tipo: TipoMovimentacaoSistema.ENTRADA,
        valor: 3500,
        periodicidade: PeriodicidadeRecorrenciaSistema.MENSAL,
        dia_execucao: 5,
        data_inicio: "2026-01-01",
        ativo: true,
        pausado: false,
        criado_em: "2026-03-03T13:11:00.000Z",
      },
    ],
    cargaMultiusuario: {
      total_usuarios_processados: 160,
      total_recorrencias_processadas: 640,
      usuario_ids_sem_vazamento: usuariosCarga,
      tempo_processamento_ms: 980,
    },
  },
  erros: {
    acessoNegado: "Usuario nao pode manipular recorrencia de outro usuario.",
    valorInvalido: "Valor da recorrencia deve ser diferente de zero.",
    diaExecucaoInvalido: "Dia de execucao invalido para periodicidade mensal.",
    recorrenciaPausada: "Recorrencia pausada nao pode gerar ocorrencias.",
  },
};
