import type { OrcamentoCategoriaDadosSimulados } from "../../tipos/orcamentos/orcamento-categoria.tipos";
import { CategoriaOrcamentoSistema } from "../../tipos/orcamentos/orcamento-categoria.tipos";

const usuarioUmId = "usuario_001";
const usuarioDoisId = "usuario_002";

const orcamentoUsuarioUmId = "orcamento_001";
const orcamentoUsuarioDoisId = "orcamento_002";

const usuariosCarga = Array.from({ length: 170 }, (_, indice) => {
  const sufixo = String(indice + 1).padStart(3, "0");
  return `usuario_orcamento_${sufixo}`;
});

export const orcamentoCategoriaDadosSimulados: OrcamentoCategoriaDadosSimulados = {
  entradas: {
    criacaoOrcamentoAlimentacaoUsuarioUm: {
      usuario_id: usuarioUmId,
      categoria: CategoriaOrcamentoSistema.ALIMENTACAO,
      competencia: "2026-03",
      moeda: "BRL",
      limite_mensal: 2000,
    },
    criacaoOrcamentoDuplicadoUsuarioUm: {
      usuario_id: usuarioUmId,
      categoria: CategoriaOrcamentoSistema.ALIMENTACAO,
      competencia: "2026-03",
      moeda: "BRL",
      limite_mensal: 2500,
    },
    criacaoOrcamentoAlimentacaoUsuarioDois: {
      usuario_id: usuarioDoisId,
      categoria: CategoriaOrcamentoSistema.ALIMENTACAO,
      competencia: "2026-03",
      moeda: "BRL",
      limite_mensal: 1800,
    },
    criacaoOrcamentoComLimiteInvalido: {
      usuario_id: usuarioUmId,
      categoria: CategoriaOrcamentoSistema.TRANSPORTE,
      competencia: "2026-03",
      moeda: "BRL",
      limite_mensal: 0,
    },
    registroConsumoAteSetentaECinco: {
      usuario_id: usuarioUmId,
      categoria: CategoriaOrcamentoSistema.ALIMENTACAO,
      competencia: "2026-03",
      valor_despesa: 1500,
      id_movimentacao: "mov_001",
    },
    registroConsumoAtingeOitenta: {
      usuario_id: usuarioUmId,
      categoria: CategoriaOrcamentoSistema.ALIMENTACAO,
      competencia: "2026-03",
      valor_despesa: 1600,
      id_movimentacao: "mov_002",
    },
    registroConsumoAtingeCem: {
      usuario_id: usuarioUmId,
      categoria: CategoriaOrcamentoSistema.ALIMENTACAO,
      competencia: "2026-03",
      valor_despesa: 2000,
      id_movimentacao: "mov_003",
    },
    registroConsumoAcimaDoLimite: {
      usuario_id: usuarioUmId,
      categoria: CategoriaOrcamentoSistema.ALIMENTACAO,
      competencia: "2026-03",
      valor_despesa: 2300,
      id_movimentacao: "mov_004",
    },
    registroEstornoReducaoConsumo: {
      usuario_id: usuarioUmId,
      categoria: CategoriaOrcamentoSistema.ALIMENTACAO,
      competencia: "2026-03",
      valor_estorno: 500,
      id_movimentacao: "mov_005",
    },
    registroConsumoOutroUsuarioNoMesmoMes: {
      usuario_id: usuarioDoisId,
      categoria: CategoriaOrcamentoSistema.ALIMENTACAO,
      competencia: "2026-03",
      valor_despesa: 500,
      id_movimentacao: "mov_006",
    },
    edicaoAumentarLimiteUsuarioUm: {
      usuario_id: usuarioUmId,
      orcamento_id: orcamentoUsuarioUmId,
      limite_mensal: 3000,
    },
    listagemOrcamentosUsuarioUm: {
      usuario_id: usuarioUmId,
      competencia: "2026-03",
      somente_ativos: true,
    },
    cargaMultiusuario: {
      usuario_ids: usuariosCarga,
      total_usuarios_esperado: 170,
      tempo_maximo_ms: 1500,
    },
  },
  resultados: {
    orcamentoCriadoUsuarioUm: {
      id: orcamentoUsuarioUmId,
      usuario_id: usuarioUmId,
      categoria: CategoriaOrcamentoSistema.ALIMENTACAO,
      competencia: "2026-03",
      moeda: "BRL",
      limite_mensal: 2000,
      valor_consumido: 0,
      percentual_consumido: 0,
      alertas_ativos: [],
      ativo: true,
      criado_em: "2026-03-03T13:20:00.000Z",
    },
    orcamentoCriadoUsuarioDois: {
      id: orcamentoUsuarioDoisId,
      usuario_id: usuarioDoisId,
      categoria: CategoriaOrcamentoSistema.ALIMENTACAO,
      competencia: "2026-03",
      moeda: "BRL",
      limite_mensal: 1800,
      valor_consumido: 0,
      percentual_consumido: 0,
      alertas_ativos: [],
      ativo: true,
      criado_em: "2026-03-03T13:21:00.000Z",
    },
    orcamentoConsumoSetentaECinco: {
      id: orcamentoUsuarioUmId,
      usuario_id: usuarioUmId,
      categoria: CategoriaOrcamentoSistema.ALIMENTACAO,
      competencia: "2026-03",
      moeda: "BRL",
      limite_mensal: 2000,
      valor_consumido: 1500,
      percentual_consumido: 75,
      alertas_ativos: [],
      ativo: true,
      criado_em: "2026-03-03T13:20:00.000Z",
    },
    orcamentoConsumoOitenta: {
      id: orcamentoUsuarioUmId,
      usuario_id: usuarioUmId,
      categoria: CategoriaOrcamentoSistema.ALIMENTACAO,
      competencia: "2026-03",
      moeda: "BRL",
      limite_mensal: 2000,
      valor_consumido: 1600,
      percentual_consumido: 80,
      alertas_ativos: ["alerta_80"],
      ativo: true,
      criado_em: "2026-03-03T13:20:00.000Z",
    },
    orcamentoConsumoCem: {
      id: orcamentoUsuarioUmId,
      usuario_id: usuarioUmId,
      categoria: CategoriaOrcamentoSistema.ALIMENTACAO,
      competencia: "2026-03",
      moeda: "BRL",
      limite_mensal: 2000,
      valor_consumido: 2000,
      percentual_consumido: 100,
      alertas_ativos: ["alerta_80", "alerta_100"],
      ativo: true,
      criado_em: "2026-03-03T13:20:00.000Z",
    },
    orcamentoConsumoAcimaDoLimite: {
      id: orcamentoUsuarioUmId,
      usuario_id: usuarioUmId,
      categoria: CategoriaOrcamentoSistema.ALIMENTACAO,
      competencia: "2026-03",
      moeda: "BRL",
      limite_mensal: 2000,
      valor_consumido: 2300,
      percentual_consumido: 115,
      alertas_ativos: ["alerta_80", "alerta_100", "acima_do_limite"],
      ativo: true,
      criado_em: "2026-03-03T13:20:00.000Z",
    },
    orcamentoAposEstorno: {
      id: orcamentoUsuarioUmId,
      usuario_id: usuarioUmId,
      categoria: CategoriaOrcamentoSistema.ALIMENTACAO,
      competencia: "2026-03",
      moeda: "BRL",
      limite_mensal: 2000,
      valor_consumido: 1800,
      percentual_consumido: 90,
      alertas_ativos: ["alerta_80"],
      ativo: true,
      criado_em: "2026-03-03T13:20:00.000Z",
    },
    orcamentoEditadoLimiteMaior: {
      id: orcamentoUsuarioUmId,
      usuario_id: usuarioUmId,
      categoria: CategoriaOrcamentoSistema.ALIMENTACAO,
      competencia: "2026-03",
      moeda: "BRL",
      limite_mensal: 3000,
      valor_consumido: 1800,
      percentual_consumido: 60,
      alertas_ativos: [],
      ativo: true,
      criado_em: "2026-03-03T13:20:00.000Z",
    },
    listagemOrcamentosUsuarioUm: [
      {
        id: orcamentoUsuarioUmId,
        usuario_id: usuarioUmId,
        categoria: CategoriaOrcamentoSistema.ALIMENTACAO,
        competencia: "2026-03",
        moeda: "BRL",
        limite_mensal: 2000,
        valor_consumido: 1500,
        percentual_consumido: 75,
        alertas_ativos: [],
        ativo: true,
        criado_em: "2026-03-03T13:20:00.000Z",
      },
    ],
    cargaMultiusuario: {
      total_usuarios_processados: 170,
      total_orcamentos_processados: 680,
      usuario_ids_sem_vazamento: usuariosCarga,
      tempo_processamento_ms: 990,
    },
  },
  erros: {
    acessoNegado: "Usuario nao pode alterar orcamento de outro usuario.",
    limiteInvalido: "Limite mensal deve ser maior que zero.",
    orcamentoDuplicadoNoMes: "Ja existe orcamento para categoria e competencia informadas.",
    orcamentoNaoEncontrado: "Orcamento nao encontrado para categoria e competencia informadas.",
  },
};
