import {
  FonteOrigemMovimentacaoSistema,
  ModoMovimentacaoSistema,
  TipoCarteiraSistema,
  TipoMovimentacaoSistema,
} from "../../tipos/sistema/financeiro.tipos";

const usuarioUmId = "usuario_001";
const usuarioDoisId = "usuario_002";

const carteiraUsuarioUmPrincipalId = "carteira_usuario_001_principal";
const carteiraUsuarioUmReservaId = "carteira_usuario_001_reserva";
const carteiraUsuarioDoisPrincipalId = "carteira_usuario_002_principal";
const carteiraUsuarioUmArquivadaId = "carteira_usuario_001_arquivada";

const usuariosLoteIds = Array.from({ length: 120 }, (_, indice) => {
  const sufixo = String(indice + 1).padStart(3, "0");
  return `usuario_lote_${sufixo}`;
});

export const carteiraDadosSimulados = {
  usuarios: {
    usuarioUm: {
      id: usuarioUmId,
      nome: "Usuario Um",
      email: "usuario.um@example.com",
      status: "ativo",
    },
    usuarioDois: {
      id: usuarioDoisId,
      nome: "Usuario Dois",
      email: "usuario.dois@example.com",
      status: "ativo",
    },
    usuariosLoteIds,
  },
  carteiras: {
    usuarioUmPrincipal: {
      id: carteiraUsuarioUmPrincipalId,
      usuario_id: usuarioUmId,
      nome: "Carteira Principal",
      tipo_carteira: TipoCarteiraSistema.CONTA_CORRENTE,
      moeda: "BRL",
      saldo_inicial: 1000,
      saldo_atual: 1000,
      ativa: true,
      arquivada: false,
      criada_em: "2026-03-03T10:00:00.000Z",
    },
    usuarioUmReserva: {
      id: carteiraUsuarioUmReservaId,
      usuario_id: usuarioUmId,
      nome: "Carteira Reserva",
      tipo_carteira: TipoCarteiraSistema.CARTEIRA_DIGITAL,
      moeda: "BRL",
      saldo_inicial: 200,
      saldo_atual: 200,
      ativa: true,
      arquivada: false,
      criada_em: "2026-03-03T10:10:00.000Z",
    },
    usuarioDoisPrincipal: {
      id: carteiraUsuarioDoisPrincipalId,
      usuario_id: usuarioDoisId,
      nome: "Carteira Principal",
      tipo_carteira: TipoCarteiraSistema.CONTA_PAGAMENTO,
      moeda: "BRL",
      saldo_inicial: 500,
      saldo_atual: 500,
      ativa: true,
      arquivada: false,
      criada_em: "2026-03-03T10:20:00.000Z",
    },
    usuarioUmArquivada: {
      id: carteiraUsuarioUmArquivadaId,
      usuario_id: usuarioUmId,
      nome: "Carteira Antiga",
      tipo_carteira: TipoCarteiraSistema.DINHEIRO,
      moeda: "BRL",
      saldo_inicial: 300,
      saldo_atual: 300,
      ativa: false,
      arquivada: true,
      criada_em: "2026-03-01T10:00:00.000Z",
    },
  },
  entradas: {
    criacaoCarteiraUsuarioUm: {
      usuario_id: usuarioUmId,
      nome: "Viagem",
      tipo_carteira: TipoCarteiraSistema.CARTEIRA_DIGITAL,
      moeda: "BRL",
      saldo_inicial: 150,
    },
    criacaoCarteiraNomeVazio: {
      usuario_id: usuarioUmId,
      nome: "",
      tipo_carteira: TipoCarteiraSistema.CARTEIRA_DIGITAL,
      moeda: "BRL",
      saldo_inicial: 0,
    },
    criacaoCarteiraDuplicadaUsuarioUm: {
      usuario_id: usuarioUmId,
      nome: "Carteira Principal",
      tipo_carteira: TipoCarteiraSistema.CONTA_CORRENTE,
      moeda: "BRL",
      saldo_inicial: 50,
    },
    criacaoCarteiraMesmoNomeUsuarioDois: {
      usuario_id: usuarioDoisId,
      nome: "Carteira Principal",
      tipo_carteira: TipoCarteiraSistema.CONTA_PAGAMENTO,
      moeda: "BRL",
      saldo_inicial: 50,
    },
    listagemCarteirasUsuarioUm: {
      usuario_id: usuarioUmId,
      incluir_arquivadas: false,
    },
    listagemCarteirasUsuarioDois: {
      usuario_id: usuarioDoisId,
      incluir_arquivadas: false,
    },
    buscaCarteiraPropria: {
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmPrincipalId,
    },
    buscaCarteiraOutroUsuario: {
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioDoisPrincipalId,
    },
    edicaoCarteiraPropria: {
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmPrincipalId,
      nome: "Carteira Principal Renomeada",
    },
    edicaoCarteiraOutroUsuario: {
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioDoisPrincipalId,
      nome: "Tentativa Indevida",
    },
    remocaoCarteiraPropria: {
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmReservaId,
    },
    remocaoCarteiraOutroUsuario: {
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioDoisPrincipalId,
    },
    remocaoCarteiraComMovimentacoesAtivas: {
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmPrincipalId,
    },
    arquivamentoCarteira: {
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmPrincipalId,
    },
    adicionarMovimentacaoEntrada: {
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmPrincipalId,
      movimentacao: {
        usuario_id: usuarioUmId,
        carteira_id: carteiraUsuarioUmPrincipalId,
        modo: ModoMovimentacaoSistema.PIX,
        tipo: TipoMovimentacaoSistema.ENTRADA,
        valor: 200,
        descricao: "Recebimento de cliente",
        data_movimentacao: "2026-03-03",
        id_origem: "mov_origem_entrada_001",
        fonte_origem: FonteOrigemMovimentacaoSistema.MANUAL,
      },
    },
    adicionarMovimentacaoSaida: {
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmPrincipalId,
      movimentacao: {
        usuario_id: usuarioUmId,
        carteira_id: carteiraUsuarioUmPrincipalId,
        modo: ModoMovimentacaoSistema.TRANSFERENCIA,
        tipo: TipoMovimentacaoSistema.SAIDA,
        valor: -200,
        descricao: "Pagamento de conta",
        data_movimentacao: "2026-03-03",
        id_origem: "mov_origem_saida_001",
        fonte_origem: FonteOrigemMovimentacaoSistema.MANUAL,
      },
    },
    adicionarMovimentacaoEmCarteiraArquivada: {
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmArquivadaId,
      movimentacao: {
        usuario_id: usuarioUmId,
        carteira_id: carteiraUsuarioUmArquivadaId,
        modo: ModoMovimentacaoSistema.DINHEIRO,
        tipo: TipoMovimentacaoSistema.ENTRADA,
        valor: 10,
        descricao: "Tentativa em carteira arquivada",
        data_movimentacao: "2026-03-03",
        id_origem: "mov_origem_arquivada_001",
        fonte_origem: FonteOrigemMovimentacaoSistema.MANUAL,
      },
    },
    transferenciaMesmoUsuario: {
      usuario_id: usuarioUmId,
      carteira_origem_id: carteiraUsuarioUmPrincipalId,
      carteira_destino_id: carteiraUsuarioUmReservaId,
      valor: 100,
      descricao: "Transferencia interna",
      data_movimentacao: "2026-03-03",
    },
    transferenciaEntreUsuarios: {
      usuario_id: usuarioUmId,
      carteira_origem_id: carteiraUsuarioUmPrincipalId,
      carteira_destino_id: carteiraUsuarioDoisPrincipalId,
      valor: 80,
      descricao: "Transferencia indevida entre usuarios",
      data_movimentacao: "2026-03-03",
    },
    importacaoCsvUsuarioUm: {
      fonte: "nubank" as const,
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmPrincipalId,
      conteudoCsv: `Data,Valor,Identificador,Descricao
10/01/2026,-50.00,id_origem_csv_001,Pagamento
11/01/2026,200.00,id_origem_csv_002,Recebimento`,
    },
    importacaoCsvDuplicadaMesmoUsuario: {
      fonte: "nubank" as const,
      usuario_id: usuarioUmId,
      carteira_id: carteiraUsuarioUmPrincipalId,
      conteudoCsv: `Data,Valor,Identificador,Descricao
10/01/2026,-50.00,id_origem_csv_001,Pagamento`,
    },
    importacaoCsvMesmoIdOutroUsuario: {
      fonte: "nubank" as const,
      usuario_id: usuarioDoisId,
      carteira_id: carteiraUsuarioDoisPrincipalId,
      conteudoCsv: `Data,Valor,Identificador,Descricao
10/01/2026,-50.00,id_origem_csv_001,Pagamento`,
    },
    listagemPaginadaUsuarioUm: {
      usuario_id: usuarioUmId,
      incluir_arquivadas: false,
      pagina: 1,
      tamanho_pagina: 2,
    },
    listagemFiltradaOrdenadaUsuarioUm: {
      usuario_id: usuarioUmId,
      incluir_arquivadas: false,
      ordenar_por: "nome" as const,
      ordem: "asc" as const,
      pagina: 1,
      tamanho_pagina: 10,
    },
    cargaMultiusuario: {
      usuario_ids: usuariosLoteIds,
      total_usuarios_esperado: 120,
      tempo_maximo_ms: 1000,
    },
  },
  resultados: {
    carteiraCriadaUsuarioUm: {
      id: "carteira_usuario_001_viagem",
      usuario_id: usuarioUmId,
      nome: "Viagem",
      tipo_carteira: TipoCarteiraSistema.CARTEIRA_DIGITAL,
      moeda: "BRL",
      saldo_inicial: 150,
      saldo_atual: 150,
      ativa: true,
      arquivada: false,
      criada_em: "2026-03-03T11:00:00.000Z",
    },
    carteiraCriadaMesmoNomeUsuarioDois: {
      id: "carteira_usuario_002_principal_nova",
      usuario_id: usuarioDoisId,
      nome: "Carteira Principal",
      tipo_carteira: TipoCarteiraSistema.CONTA_PAGAMENTO,
      moeda: "BRL",
      saldo_inicial: 50,
      saldo_atual: 50,
      ativa: true,
      arquivada: false,
      criada_em: "2026-03-03T11:05:00.000Z",
    },
    listaCarteirasUsuarioUm: [
      {
        id: carteiraUsuarioUmPrincipalId,
        usuario_id: usuarioUmId,
        nome: "Carteira Principal",
        tipo_carteira: TipoCarteiraSistema.CONTA_CORRENTE,
        moeda: "BRL",
        saldo_inicial: 1000,
        saldo_atual: 1000,
        ativa: true,
        arquivada: false,
        criada_em: "2026-03-03T10:00:00.000Z",
      },
      {
        id: carteiraUsuarioUmReservaId,
        usuario_id: usuarioUmId,
        nome: "Carteira Reserva",
        tipo_carteira: TipoCarteiraSistema.CARTEIRA_DIGITAL,
        moeda: "BRL",
        saldo_inicial: 200,
        saldo_atual: 200,
        ativa: true,
        arquivada: false,
        criada_em: "2026-03-03T10:10:00.000Z",
      },
    ],
    carteiraEditadaUsuarioUm: {
      id: carteiraUsuarioUmPrincipalId,
      usuario_id: usuarioUmId,
      nome: "Carteira Principal Renomeada",
      tipo_carteira: TipoCarteiraSistema.CONTA_CORRENTE,
      moeda: "BRL",
      saldo_inicial: 1000,
      saldo_atual: 1000,
      ativa: true,
      arquivada: false,
      criada_em: "2026-03-03T10:00:00.000Z",
    },
    carteiraArquivadaUsuarioUm: {
      id: carteiraUsuarioUmPrincipalId,
      usuario_id: usuarioUmId,
      nome: "Carteira Principal",
      tipo_carteira: TipoCarteiraSistema.CONTA_CORRENTE,
      moeda: "BRL",
      saldo_inicial: 1000,
      saldo_atual: 1000,
      ativa: false,
      arquivada: true,
      criada_em: "2026-03-03T10:00:00.000Z",
    },
    carteiraSaldoAposEntrada: {
      id: carteiraUsuarioUmPrincipalId,
      usuario_id: usuarioUmId,
      nome: "Carteira Principal",
      tipo_carteira: TipoCarteiraSistema.CONTA_CORRENTE,
      moeda: "BRL",
      saldo_inicial: 1000,
      saldo_atual: 1200,
      ativa: true,
      arquivada: false,
      criada_em: "2026-03-03T10:00:00.000Z",
    },
    carteiraSaldoAposSaida: {
      id: carteiraUsuarioUmPrincipalId,
      usuario_id: usuarioUmId,
      nome: "Carteira Principal",
      tipo_carteira: TipoCarteiraSistema.CONTA_CORRENTE,
      moeda: "BRL",
      saldo_inicial: 1000,
      saldo_atual: 800,
      ativa: true,
      arquivada: false,
      criada_em: "2026-03-03T10:00:00.000Z",
    },
    resultadoTransferenciaMesmoUsuario: {
      movimentacao_debito: {
        usuario_id: usuarioUmId,
        carteira_id: carteiraUsuarioUmPrincipalId,
        modo: ModoMovimentacaoSistema.TRANSFERENCIA,
        tipo: TipoMovimentacaoSistema.SAIDA,
        valor: -100,
        descricao: "Transferencia interna",
        data_movimentacao: "2026-03-03",
        fonte_origem: FonteOrigemMovimentacaoSistema.MANUAL,
      },
      movimentacao_credito: {
        usuario_id: usuarioUmId,
        carteira_id: carteiraUsuarioUmReservaId,
        modo: ModoMovimentacaoSistema.TRANSFERENCIA,
        tipo: TipoMovimentacaoSistema.ENTRADA,
        valor: 100,
        descricao: "Transferencia interna",
        data_movimentacao: "2026-03-03",
        fonte_origem: FonteOrigemMovimentacaoSistema.MANUAL,
      },
      saldo_origem: 900,
      saldo_destino: 300,
    },
    resultadoImportacaoCsvUsuarioUm: {
      movimentacoes_criadas: 2,
      movimentacoes_ignoradas_duplicadas: 0,
      ids_origem_criados: ["id_origem_csv_001", "id_origem_csv_002"],
      ids_origem_ignorados: [],
    },
    resultadoImportacaoCsvDuplicadaMesmoUsuario: {
      movimentacoes_criadas: 0,
      movimentacoes_ignoradas_duplicadas: 1,
      ids_origem_criados: [],
      ids_origem_ignorados: ["id_origem_csv_001"],
    },
    resultadoImportacaoCsvMesmoIdOutroUsuario: {
      movimentacoes_criadas: 1,
      movimentacoes_ignoradas_duplicadas: 0,
      ids_origem_criados: ["id_origem_csv_001"],
      ids_origem_ignorados: [],
    },
    resultadoListagemPaginadaUsuarioUm: {
      itens: [
        {
          id: carteiraUsuarioUmPrincipalId,
          usuario_id: usuarioUmId,
          nome: "Carteira Principal",
          tipo_carteira: TipoCarteiraSistema.CONTA_CORRENTE,
          moeda: "BRL",
          saldo_inicial: 1000,
          saldo_atual: 1000,
          ativa: true,
          arquivada: false,
          criada_em: "2026-03-03T10:00:00.000Z",
        },
        {
          id: carteiraUsuarioUmReservaId,
          usuario_id: usuarioUmId,
          nome: "Carteira Reserva",
          tipo_carteira: TipoCarteiraSistema.CARTEIRA_DIGITAL,
          moeda: "BRL",
          saldo_inicial: 200,
          saldo_atual: 200,
          ativa: true,
          arquivada: false,
          criada_em: "2026-03-03T10:10:00.000Z",
        },
      ],
      pagina: 1,
      tamanho_pagina: 2,
      total_itens: 2,
      total_paginas: 1,
    },
    resultadoListagemFiltradaOrdenadaUsuarioUm: {
      itens: [
        {
          id: carteiraUsuarioUmPrincipalId,
          usuario_id: usuarioUmId,
          nome: "Carteira Principal",
          tipo_carteira: TipoCarteiraSistema.CONTA_CORRENTE,
          moeda: "BRL",
          saldo_inicial: 1000,
          saldo_atual: 1000,
          ativa: true,
          arquivada: false,
          criada_em: "2026-03-03T10:00:00.000Z",
        },
        {
          id: carteiraUsuarioUmReservaId,
          usuario_id: usuarioUmId,
          nome: "Carteira Reserva",
          tipo_carteira: TipoCarteiraSistema.CARTEIRA_DIGITAL,
          moeda: "BRL",
          saldo_inicial: 200,
          saldo_atual: 200,
          ativa: true,
          arquivada: false,
          criada_em: "2026-03-03T10:10:00.000Z",
        },
      ],
      pagina: 1,
      tamanho_pagina: 10,
      total_itens: 2,
      total_paginas: 1,
    },
    resultadoCargaMultiusuario: {
      total_usuarios_processados: 120,
      total_carteiras_processadas: 240,
      usuario_ids_sem_vazamento: usuariosLoteIds,
      tempo_processamento_ms: 420,
    },
  },
  erros: {
    nomeVazio: "Nome da carteira nao pode ser vazio.",
    carteiraDuplicada: "Carteira duplicada para o mesmo usuario.",
    acessoNegado: "Acesso negado para esta carteira.",
    carteiraComMovimentacoesAtivas:
      "Nao e permitido remover carteira com movimentacoes ativas.",
    carteiraArquivada: "Carteira arquivada nao aceita movimentacao.",
    transferenciaEntreUsuariosBloqueada:
      "Transferencia entre usuarios diferentes nao e permitida.",
    conflitoConcorrencia: "Conflito de concorrencia detectado.",
    saldoInconsistente: "Inconsistencia de saldo detectada.",
  },
};
